import { Club, Event, ESGProject, Document, Notification, User, FanTier, FanAction, FanReward, FanProfile, FanZoneStats } from "./types";

// ===== MOCK USER =====
export const mockUser: User = {
  id: "u2",
  name: "Felipe González",
  email: "felipe@clubrugby.cl",
  role: "club",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
  club: "Rugby Verde",
  country: "Chile",
  clubId: "c4",
};

// ===== MOCK USERS (one per role) =====
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Carlos Rodríguez",
    email: "carlos@bettersport.com",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    club: "BetterSport Platform",
    country: "España",
  },
  {
    id: "u2",
    name: "Felipe González",
    email: "felipe@clubrugby.cl",
    role: "club",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
    club: "Rugby Verde",
    country: "Chile",
    clubId: "c4",
  },
  {
    id: "u3",
    name: "Alejandro Reyes",
    email: "alejandro@greensportsa.com",
    role: "brand",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro",
    club: "GreenSport SA",
    country: "Argentina",
  },
  {
    id: "u5",
    name: "Sergio Blanco",
    email: "sergio@ecosolutions.com",
    role: "solucion",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sergio",
    club: "EcoSolutions Sport",
    country: "Colombia",
  },
  {
    id: "u7",
    name: "Martina Herrera",
    email: "martina@fanzone.com",
    role: "hincha",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Martina",
    club: "Rugby Verde",
    country: "Chile",
    clubId: "c4",
  },
];

// ===== MOCK CLUBS (RANKING) =====
export const mockClubs: Club[] = [
  {
    id: "c1",
    name: "Colo-Colo",
    sport: "Fútbol",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 94.2,
    ranking: 1,
    environmental: 96,
    social: 93,
    governance: 91,
    transparency: 98,
    members: 45000,
    founded: 1925,
    description: "El club más ganador del fútbol chileno, líer en sostenibilidad deportiva.",
  },
  {
    id: "c2",
    name: "Universidad de Chile",
    sport: "Fútbol",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 91.8,
    ranking: 2,
    environmental: 94,
    social: 90,
    governance: 89,
    transparency: 94,
    members: 38000,
    founded: 1927,
    description: "El Bulla, referente en inclusión social y gestión ambiental.",
  },
  {
    id: "c3",
    name: "Padel Eco Club",
    sport: "Pádel",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 88.5,
    ranking: 3,
    environmental: 90,
    social: 88,
    governance: 85,
    transparency: 91,
    members: 650,
    founded: 2005,
    description: "Inclusión y medio ambiente, nuestra razón de ser.",
  },
  {
    id: "c4",
    name: "Rugby Verde",
    sport: "Rugby",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 85.3,
    ranking: 4,
    environmental: 87,
    social: 84,
    governance: 83,
    transparency: 87,
    members: 420,
    founded: 1998,
    description: "Rugby con conciencia ambiental y social.",
  },
  {
    id: "c5",
    name: "Natación Inclusiva",
    sport: "Natación",
    country: "Colombia",
    flag: "🇨🇴",
    esgScore: 82.1,
    ranking: 5,
    environmental: 80,
    social: 90,
    governance: 79,
    transparency: 82,
    members: 310,
    founded: 2010,
    description: "Deporte adaptado e inclusión social.",
  },
  {
    id: "c6",
    name: "Tenis Sustentable",
    sport: "Tenis",
    country: "México",
    flag: "🇲🇽",
    esgScore: 79.6,
    ranking: 6,
    environmental: 82,
    social: 78,
    governance: 76,
    transparency: 83,
    members: 890,
    founded: 2001,
    description: "Promoviendo el tenis verde.",
  },
  {
    id: "c7",
    name: "Atletismo Comunitario",
    sport: "Atletismo",
    country: "Perú",
    flag: "🇵🇪",
    esgScore: 76.4,
    ranking: 7,
    environmental: 74,
    social: 82,
    governance: 74,
    transparency: 80,
    members: 520,
    founded: 2008,
    description: "Atletismo para todos.",
  },
  {
    id: "c8",
    name: "Fútbol Barrial",
    sport: "Fútbol",
    country: "Uruguay",
    flag: "🇺🇾",
    esgScore: 73.2,
    ranking: 8,
    environmental: 71,
    social: 79,
    governance: 70,
    transparency: 74,
    members: 1100,
    founded: 1975,
    description: "El fútbol como herramienta social.",
  },
  {
    id: "c9",
    name: "CrossFit Sostenible Madrid",
    sport: "CrossFit",
    country: "España",
    flag: "🇪🇸",
    esgScore: 71.4,
    ranking: 9,
    environmental: 69,
    social: 75,
    governance: 69,
    transparency: 73,
    members: 420,
    founded: 2015,
    description: "CrossFit con enfoque comunitario y sostenible en Madrid.",
  },
  {
    id: "c10",
    name: "Voleibol Ecológico Bogotá",
    sport: "Voleibol",
    country: "Colombia",
    flag: "🇨🇴",
    esgScore: 68.9,
    ranking: 10,
    environmental: 70,
    social: 72,
    governance: 64,
    transparency: 70,
    members: 280,
    founded: 2012,
    description: "Deporte y naturaleza en perfecta armonía en Bogotá.",
  },
  {
    id: "c11",
    name: "Básquetbol Social Buenos Aires",
    sport: "Básquetbol",
    country: "Argentina",
    flag: "🇦🇷",
    esgScore: 66.2,
    ranking: 11,
    environmental: 64,
    social: 70,
    governance: 65,
    transparency: 66,
    members: 650,
    founded: 2009,
    description: "Básquetbol comprometido con el desarrollo social y comunitario.",
  },
  {
    id: "c12",
    name: "Trail Running Patagonia",
    sport: "Trail Running",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 63.7,
    ranking: 12,
    environmental: 68,
    social: 62,
    governance: 59,
    transparency: 66,
    members: 190,
    founded: 2018,
    description: "Corredores de montaña con profunda conciencia ambiental.",
  },
  {
    id: "c13",
    name: "Handball Inclusivo CDMX",
    sport: "Handball",
    country: "México",
    flag: "🇲🇽",
    esgScore: 60.5,
    ranking: 13,
    environmental: 58,
    social: 67,
    governance: 57,
    transparency: 60,
    members: 340,
    founded: 2014,
    description: "Handball para todas las edades y capacidades en Ciudad de México.",
  },
  {
    id: "c14",
    name: "Ciclismo Urbano BCN",
    sport: "Ciclismo",
    country: "España",
    flag: "🇪🇸",
    esgScore: 57.8,
    ranking: 14,
    environmental: 62,
    social: 56,
    governance: 53,
    transparency: 60,
    members: 780,
    founded: 2016,
    description: "Movilidad sostenible y deporte urbano en Barcelona.",
  },
  {
    id: "c15",
    name: "Boxeo Social Lima",
    sport: "Boxeo",
    country: "Perú",
    flag: "🇵🇪",
    esgScore: 54.1,
    ranking: 15,
    environmental: 50,
    social: 62,
    governance: 51,
    transparency: 54,
    members: 210,
    founded: 2020,
    description: "Boxeo como herramienta de inclusión social en Lima.",
  },
  {
    id: "c16",
    name: "Deportes Temuco",
    sport: "Fútbol",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 78.4,
    ranking: 6,
    environmental: 80,
    social: 79,
    governance: 75,
    transparency: 80,
    members: 12000,
    founded: 1969,
    description: "El Coihueco, referente del fútbol de La Araucanía con fuerte compromiso social y ambiental.",
  },
  {
    id: "c17",
    name: "Universidad Católica",
    sport: "Fútbol",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 87.1,
    ranking: 3,
    environmental: 89,
    social: 86,
    governance: 85,
    transparency: 89,
    members: 35000,
    founded: 1937,
    description: "La Franja, uno de los clubes más exitosos del fútbol chileno con sólida gestión ESG.",
  },
];

// ===== MOCK EVENTS =====
export const mockEvents: Event[] = [
  {
    id: "e1",
    title: "Descarbonizando el rugby",
    clubId: "c4",
    clubName: "Rugby Verde",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Rugby",
    category: "huella_carbono",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos y reducción de huella de carbono.",
    sustainableImpact: "Reducción del 40% de emisiones CO2 en 3 temporadas",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["Federación Rugby Chile"],
    mediaPartner: "CNN",
    sealEsg: true,
    audience: 15000,
    status: "negotiating",
  },
  {
    id: "e2",
    title: "Agua para el fútbol",
    clubId: "c2",
    clubName: "Green Sports FC",
    country: "Argentina",
    flag: "🇦🇷",
    sport: "Fútbol",
    category: "huella_hidrica",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos y eficiencia hídrica.",
    sustainableImpact: "Ahorro de 500.000 litros de agua por temporada",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["AquaEco"],
    mediaPartner: "CNN",
    sealEsg: true,
    audience: 45000,
    status: "negotiating",
  },
  {
    id: "e3",
    title: "Inclusión en Padel",
    clubId: "c3",
    clubName: "Padel Eco Club",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Pádel",
    category: "inclusion",
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos e inclusión deportiva.",
    sustainableImpact: "200 personas con discapacidad integradas al deporte",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["World Padel Tour"],
    mediaPartner: "ESPN",
    sealEsg: true,
    audience: 8000,
    status: "negotiating",
  },
  {
    id: "e4",
    title: "Gestión residuos en estadios",
    clubId: "c1",
    clubName: "Club Atlético Sostenible",
    country: "España",
    flag: "🇪🇸",
    sport: "Fútbol",
    category: "gestion_residuos",
    image: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&q=80",
    description: "Implementación de sistema de reciclaje y compostaje en estadios deportivos.",
    sustainableImpact: "Reciclaje del 80% de residuos generados en eventos",
    budget: 85000,
    funded: 60000,
    remaining: 25000,
    daysLeft: 12,
    sealEsg: false,
    audience: 60000,
    status: "open",
  },
  {
    id: "e5",
    title: "Educación ambiental juvenil",
    clubId: "c5",
    clubName: "Natación Inclusiva",
    country: "Colombia",
    flag: "🇨🇴",
    sport: "Natación",
    category: "educacion",
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80",
    description: "Programa educativo para jóvenes deportistas sobre sostenibilidad y cuidado del medioambiente.",
    sustainableImpact: "1.000 jóvenes capacitados en conciencia ambiental",
    budget: 45000,
    funded: 35000,
    remaining: 10000,
    daysLeft: 21,
    sealEsg: true,
    audience: 5000,
    status: "negotiating",
  },
  {
    id: "e6",
    title: "Equidad de género en el deporte",
    clubId: "c6",
    clubName: "Tenis Sustentable",
    country: "México",
    flag: "🇲🇽",
    sport: "Tenis",
    category: "equidad_genero",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600&q=80",
    description: "Programa de becas y formación para atletas femeninas de bajos recursos.",
    sustainableImpact: "150 mujeres acceden a formación deportiva de élite",
    budget: 65000,
    funded: 40000,
    remaining: 25000,
    daysLeft: 30,
    sealEsg: true,
    audience: 12000,
    status: "open",
  },
  {
    id: "e7",
    title: "Maratón Verde — Cero Emisiones",
    clubId: "c7",
    clubName: "Atletismo Comunitario",
    country: "Perú",
    flag: "🇵🇪",
    sport: "Atletismo",
    category: "huella_carbono",
    image: "https://images.unsplash.com/photo-1530143311094-34d807799e8f?w=600&q=80",
    description: "Maratón urbana con cero emisiones netas. Cada corredor planta un árbol al cruzar la meta.",
    sustainableImpact: "500 árboles plantados, certificación carbono neutro",
    budget: 55000,
    funded: 30000,
    remaining: 25000,
    daysLeft: 45,
    sealEsg: true,
    audience: 8000,
    status: "open",
    featured: true,
  },
  {
    id: "e8",
    title: "Rugby Femenino Sin Fronteras",
    clubId: "c4",
    clubName: "Rugby Verde",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Rugby",
    category: "equidad_genero",
    image: "https://images.unsplash.com/photo-1546519638405-a9f9a7c5d0b5?w=600&q=80",
    description: "Torneo internacional femenino de rugby con enfoque en equidad de género e inclusión.",
    sustainableImpact: "80 jugadoras de 10 países, programa de becas activo",
    budget: 78000,
    funded: 50000,
    remaining: 28000,
    daysLeft: 60,
    sponsoredBy: ["ONU Mujeres", "Nike"],
    sealEsg: true,
    audience: 22000,
    status: "open",
  },
  {
    id: "e9",
    title: "Torneo Pádel Cero Residuos",
    clubId: "c3",
    clubName: "Padel Eco Club",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Pádel",
    category: "gestion_residuos",
    image: "https://images.unsplash.com/photo-1551958219-acbc595d66cf?w=600&q=80",
    description: "Torneo regional de pádel con sistema de cero residuos: sin plásticos de un solo uso y compostaje en cancha.",
    sustainableImpact: "100% residuos reciclados, 0 plásticos de un solo uso",
    budget: 35000,
    funded: 20000,
    remaining: 15000,
    daysLeft: 18,
    sealEsg: false,
    audience: 3500,
    status: "negotiating",
  },
  {
    id: "e10",
    title: "Escuela de Natación Comunitaria",
    clubId: "c5",
    clubName: "Natación Inclusiva",
    country: "Colombia",
    flag: "🇨🇴",
    sport: "Natación",
    category: "inclusion",
    image: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=600&q=80",
    description: "Escuela de natación gratuita para niños de zonas vulnerables, con énfasis en seguridad acuática y deporte inclusivo.",
    sustainableImpact: "300 niños aprenden a nadar, reducción de accidentes acuáticos",
    budget: 28000,
    funded: 28000,
    remaining: 0,
    daysLeft: 0,
    sponsoredBy: ["Fondo Nacional Deportivo", "Coldeportes"],
    sealEsg: true,
    audience: 4500,
    status: "funded",
  },
];

// ===== MOCK ESG PROJECTS =====
export const mockESGProjects: ESGProject[] = [
  {
    id: "p1",
    title: "Reducción huella de carbono 2025",
    category: "huella_carbono",
    status: "in_progress",
    progress: 65,
    budget: 45000,
    spent: 29250,
    startDate: "2025-01-15",
    endDate: "2025-12-31",
    responsible: "Carlos Mendoza",
    description: "Reducir las emisiones de CO2 del club en un 40% mediante energías renovables y movilidad sostenible.",
    milestones: [
      { id: "m1", title: "Auditoría inicial de emisiones", date: "2025-02-01", completed: true },
      { id: "m2", title: "Instalación paneles solares", date: "2025-05-01", completed: true },
      { id: "m3", title: "Flota vehículos eléctricos", date: "2025-08-01", completed: false },
      { id: "m4", title: "Certificación ISO 14001", date: "2025-12-01", completed: false },
    ],
    kpis: [
      { id: "k1", name: "Emisiones CO2 (ton)", current: 24, target: 18, unit: "ton", trend: "down" },
      { id: "k2", name: "Energía renovable (%)", current: 65, target: 100, unit: "%", trend: "up" },
    ],
  },
  {
    id: "p2",
    title: "Programa inclusión social 2025",
    category: "inclusion",
    status: "in_progress",
    progress: 80,
    budget: 28000,
    spent: 22400,
    startDate: "2025-03-01",
    endDate: "2025-11-30",
    responsible: "Ana Ruiz",
    description: "Incorporar 200 personas en situación de vulnerabilidad al deporte.",
    milestones: [
      { id: "m5", title: "Convenio municipalidad", date: "2025-03-15", completed: true },
      { id: "m6", title: "Primera cohorte inscrita", date: "2025-04-15", completed: true },
      { id: "m7", title: "Evaluación semestral", date: "2025-08-30", completed: true },
      { id: "m8", title: "Informe final y certificación", date: "2025-11-30", completed: false },
    ],
    kpis: [
      { id: "k3", name: "Personas incluidas", current: 160, target: 200, unit: "personas", trend: "up" },
      { id: "k4", name: "Tasa retención (%)", current: 82, target: 80, unit: "%", trend: "up" },
    ],
  },
  {
    id: "p3",
    title: "Gestión hídrica instalaciones",
    category: "huella_hidrica",
    status: "planning",
    progress: 20,
    budget: 18000,
    spent: 3600,
    startDate: "2025-09-01",
    endDate: "2026-03-31",
    responsible: "Pedro Soto",
    description: "Optimizar el uso del agua en canchas e instalaciones deportivas.",
    milestones: [
      { id: "m9", title: "Auditoría hídrica", date: "2025-09-30", completed: true },
      { id: "m10", title: "Sistema captación agua lluvia", date: "2025-12-01", completed: false },
      { id: "m11", title: "Riego inteligente", date: "2026-02-01", completed: false },
    ],
    kpis: [
      { id: "k5", name: "Consumo agua (m³/mes)", current: 1200, target: 800, unit: "m³", trend: "down" },
    ],
  },
  {
    id: "p4",
    title: "Equidad de género en directiva 2025",
    category: "equidad_genero",
    status: "in_progress",
    progress: 50,
    budget: 12000,
    spent: 6000,
    startDate: "2025-04-01",
    endDate: "2025-12-31",
    responsible: "María Torres",
    description: "Implementar política de género para alcanzar 40% de participación femenina en órganos directivos.",
    milestones: [
      { id: "m12", title: "Diagnóstico de brechas de género", date: "2025-04-30", completed: true },
      { id: "m13", title: "Política de género aprobada en asamblea", date: "2025-06-30", completed: true },
      { id: "m14", title: "Elecciones con cupo femenino", date: "2025-09-30", completed: false },
      { id: "m15", title: "Informe de cumplimiento anual", date: "2025-12-15", completed: false },
    ],
    kpis: [
      { id: "k6", name: "Mujeres en directiva (%)", current: 25, target: 40, unit: "%", trend: "up" },
      { id: "k7", name: "Deportistas femeninas activas", current: 85, target: 120, unit: "personas", trend: "up" },
    ],
  },
  {
    id: "p5",
    title: "Educación ambiental categorías menores",
    category: "educacion",
    status: "completed",
    progress: 100,
    budget: 8500,
    spent: 8200,
    startDate: "2025-02-01",
    endDate: "2025-07-31",
    responsible: "Sofía Morales",
    description: "Programa de 6 meses de educación ambiental para atletas menores de 18 años.",
    milestones: [
      { id: "m16", title: "Diseño curricular del programa", date: "2025-02-28", completed: true },
      { id: "m17", title: "Capacitación de monitores", date: "2025-03-31", completed: true },
      { id: "m18", title: "Implementación del programa", date: "2025-06-30", completed: true },
      { id: "m19", title: "Evaluación final y certificación", date: "2025-07-31", completed: true },
    ],
    kpis: [
      { id: "k8", name: "Jóvenes capacitados", current: 124, target: 100, unit: "personas", trend: "up" },
      { id: "k9", name: "Talleres realizados", current: 18, target: 18, unit: "talleres", trend: "stable" },
    ],
  },
];

// ===== MOCK DOCUMENTS =====
export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "Política ESG Club Rugby Chile 2025.pdf",
    type: "pdf",
    category: "Política ESG",
    size: "2.4 MB",
    uploadedAt: "2025-01-10",
    uploadedBy: "Felipe González",
    version: "v2.0",
  },
  {
    id: "d2",
    name: "Reporte Carbono Q1 2025.xlsx",
    type: "xls",
    category: "Ambiental",
    size: "845 KB",
    uploadedAt: "2025-04-05",
    uploadedBy: "Carlos Mendoza",
    version: "v1.0",
  },
  {
    id: "d3",
    name: "Certificado ISO 14001 Borrador.pdf",
    type: "pdf",
    category: "Certificaciones",
    size: "1.2 MB",
    uploadedAt: "2025-05-20",
    uploadedBy: "Felipe González",
    version: "v1.0",
  },
  {
    id: "d4",
    name: "Evidencias inclusión social - fotos.zip",
    type: "img",
    category: "Social",
    size: "18.5 MB",
    uploadedAt: "2025-06-01",
    uploadedBy: "Ana Ruiz",
    version: "v1.0",
  },
  {
    id: "d5",
    name: "Presupuesto proyectos ESG 2025.xlsx",
    type: "xls",
    category: "Financiero",
    size: "320 KB",
    uploadedAt: "2025-01-05",
    uploadedBy: "Pedro Soto",
    version: "v3.1",
  },
];

// ===== MOCK NOTIFICATIONS =====
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "success",
    title: "Propuesta aceptada",
    message: "Claro aceptó tu propuesta de patrocinio para 'Descarbonizando el rugby'",
    time: "Hace 2 horas",
    read: false,
  },
  {
    id: "n2",
    type: "warning",
    title: "KPI fuera de meta",
    message: "El indicador de consumo hídrico supera el límite mensual",
    time: "Hace 5 horas",
    read: false,
  },
  {
    id: "n3",
    type: "info",
    title: "Nueva propuesta recibida",
    message: "ESPN envió una propuesta de media partner para 'Agua para el fútbol'",
    time: "Hace 1 día",
    read: true,
  },
  {
    id: "n4",
    type: "info",
    title: "Ranking actualizado",
    message: "Tu club subió al puesto #4 en el ranking de sostenibilidad",
    time: "Hace 2 días",
    read: true,
  },
];

// ===== ESG CATEGORY LABELS =====
export const categoryLabels: Record<string, string> = {
  huella_hidrica: "Huella hídrica",
  huella_carbono: "Huella de carbono",
  gestion_residuos: "Gestión de residuos",
  educacion: "Educación",
  inclusion: "Inclusión",
  equidad_genero: "Equidad de género",
};

export const categoryColors: Record<string, string> = {
  huella_hidrica: "badge-cyan",
  huella_carbono: "badge-green",
  gestion_residuos: "badge-orange",
  educacion: "badge-blue",
  inclusion: "badge-purple",
  equidad_genero: "badge-red",
};

export const categoryIcons: Record<string, string> = {
  huella_hidrica: "💧",
  huella_carbono: "🌱",
  gestion_residuos: "♻️",
  educacion: "📚",
  inclusion: "🤝",
  equidad_genero: "⚖️",
};

// ===== SOLUTIONS / PROVIDERS =====

import type { SolutionProvider } from "./types";

export const solutionCategoryLabels: Record<string, string> = {
  eficiencia_hidrica: "Eficiencia hídrica",
  eficiencia_energetica: "Eficiencia energética",
  gestion_residuos: "Gestión de residuos",
  educacion_ambiental: "Educación ambiental",
  impacto_social: "Impacto social",
  movilidad_sostenible: "Movilidad sostenible",
};

export const solutionCategoryIcons: Record<string, string> = {
  eficiencia_hidrica: "💧",
  eficiencia_energetica: "⚡",
  gestion_residuos: "♻️",
  educacion_ambiental: "🌿",
  impacto_social: "🤝",
  movilidad_sostenible: "🚲",
};

export const mockSolutionProviders: SolutionProvider[] = [
  {
    id: "sp1",
    name: "AquaTech Solutions",
    initials: "AT",
    color: "#0EA5E9",
    category: "eficiencia_hidrica",
    country: "Chile",
    flag: "🇨🇱",
    description: "Especialistas en sistemas de captura y reutilización de agua pluvial para estadios y recintos deportivos. Reducimos hasta un 60% el consumo hídrico.",
    services: ["Auditoría hídrica", "Sistemas de captación", "Monitoreo IoT", "Certificación hídrica"],
    projectsCount: 50,
    associatedBrand: "Claro",
    associatedClub: "Universidad de Chile",
    stars: 5,
    verified: true,
    featured: true,
    tags: ["IoT", "Estadios", "Certificación"],
  },
  {
    id: "sp2",
    name: "GreenEnergy Sport",
    initials: "GE",
    color: "#10B981",
    category: "eficiencia_energetica",
    country: "Argentina",
    flag: "🇦🇷",
    description: "Instalación de paneles solares y sistemas de iluminación LED de alta eficiencia para instalaciones deportivas. Partner oficial de la ANFP.",
    services: ["Paneles solares", "LED deportivo", "Auditoría energética", "Compensación CO₂"],
    projectsCount: 45,
    associatedBrand: "ESPN",
    associatedClub: "Boca Juniors",
    stars: 4,
    verified: true,
    featured: true,
    tags: ["Solar", "LED", "ANFP"],
  },
  {
    id: "sp3",
    name: "Ciclo Verde",
    initials: "CV",
    color: "#F59E0B",
    category: "gestion_residuos",
    country: "Chile",
    flag: "🇨🇱",
    description: "Gestión integral de residuos en eventos deportivos masivos. Implementamos estaciones de clasificación, compostaje y economía circular en estadios.",
    services: ["Plan de residuos cero", "Estaciones de reciclaje", "Compostaje orgánico", "Reporte de impacto"],
    projectsCount: 40,
    associatedBrand: "VTR",
    associatedClub: "Colo-Colo",
    stars: 4,
    verified: true,
    tags: ["Eventos", "Reciclaje", "Economía circular"],
  },
  {
    id: "sp4",
    name: "EduSport Sostenible",
    initials: "ES",
    color: "#8B5CF6",
    category: "educacion_ambiental",
    country: "Chile",
    flag: "🇨🇱",
    description: "Programas educativos sobre sostenibilidad y medioambiente dirigidos a clubes, federaciones y comunidades deportivas de toda Latinoamérica.",
    services: ["Talleres formativos", "Curriculum ESG para clubes", "Campañas de sensibilización", "Certificados de formación"],
    projectsCount: 30,
    associatedBrand: "Itaú",
    associatedClub: "La Serena",
    stars: 4,
    verified: true,
    featured: true,
    tags: ["Formación", "LATAM", "Certificados"],
  },
  {
    id: "sp5",
    name: "MoviSport",
    initials: "MS",
    color: "#06B6D4",
    category: "movilidad_sostenible",
    country: "Chile",
    flag: "🇨🇱",
    description: "Implementamos planes de movilidad sostenible para recintos deportivos: bicicleteros, zonas de carga eléctrica y convenios con apps de transporte compartido.",
    services: ["Bicicleteros seguros", "Carga vehículos eléctricos", "Parkings inteligentes", "Plan de movilidad"],
    projectsCount: 25,
    associatedBrand: "Pemex",
    associatedClub: "Atlético Nacional",
    stars: 4,
    verified: true,
    tags: ["Bicicleta", "Eléctrico", "Smart parking"],
  },
  {
    id: "sp6",
    name: "ImpactoClub",
    initials: "IC",
    color: "#EC4899",
    category: "impacto_social",
    country: "México",
    flag: "🇲🇽",
    description: "Diseñamos programas de inclusión, diversidad y equidad de género para organizaciones deportivas, con métricas de impacto social certificadas.",
    services: ["Diagnóstico DEI", "Programas de inclusión", "Métricas de impacto", "Reportes sociales"],
    projectsCount: 23,
    associatedBrand: "Águila",
    associatedClub: "América de Cali",
    stars: 4,
    verified: true,
    tags: ["DEI", "Inclusión", "Métricas"],
  },
  {
    id: "sp7",
    name: "HidroSport CL",
    initials: "HS",
    color: "#0284C7",
    category: "eficiencia_hidrica",
    country: "Chile",
    flag: "🇨🇱",
    description: "Sistemas de riego inteligente y mantenimiento de canchas con mínimo consumo de agua. Especialistas en campos de fútbol y tenis.",
    services: ["Riego inteligente", "Sensores de humedad", "Mantenimiento césped", "Reciclaje de agua"],
    projectsCount: 18,
    associatedBrand: "Claro",
    associatedClub: "Huachipato",
    stars: 3,
    verified: true,
    tags: ["Riego", "Fútbol", "Tenis"],
  },
  {
    id: "sp8",
    name: "SolarStadium",
    initials: "SS",
    color: "#F97316",
    category: "eficiencia_energetica",
    country: "España",
    flag: "🇪🇸",
    description: "Referentes europeos en energía renovable para estadios y pabellones deportivos. Proyectos en más de 40 recintos en Europa y Latinoamérica.",
    services: ["Plantas solares", "Baterías de almacenamiento", "Power Purchase Agreement", "Carbon neutral"],
    projectsCount: 15,
    associatedBrand: "ESPN",
    associatedClub: "Barcelona SC",
    stars: 5,
    verified: true,
    featured: true,
    tags: ["Europa", "Carbon neutral", "PPA"],
  },
  {
    id: "sp9",
    name: "ResidúOK",
    initials: "RO",
    color: "#84CC16",
    category: "gestion_residuos",
    country: "Chile",
    flag: "🇨🇱",
    description: "App y servicio de logística para la correcta disposición de residuos generados en torneos y eventos deportivos de cualquier escala.",
    services: ["App de trazabilidad", "Retiro programado", "Informe de disposición", "Certificados legales"],
    projectsCount: 12,
    associatedBrand: "VTR",
    associatedClub: "O'Higgins",
    stars: 3,
    verified: true,
    tags: ["App", "Logística", "Certificados"],
  },
];

// ===== FAN ZONE =====

export const fanTiers: FanTier[] = [
  { name: "bronce",  label: "Bronce",  emoji: "🥉", minPoints: 0,    maxPoints: 499,      color: "#CD7F32", glowColor: "rgba(205,127,50,0.25)"  },
  { name: "plata",   label: "Plata",   emoji: "🥈", minPoints: 500,  maxPoints: 1499,     color: "#94A3B8", glowColor: "rgba(148,163,184,0.25)" },
  { name: "oro",     label: "Oro",     emoji: "🥇", minPoints: 1500, maxPoints: 3999,     color: "#F59E0B", glowColor: "rgba(245,158,11,0.25)"  },
  { name: "leyenda", label: "Leyenda", emoji: "🌟", minPoints: 4000, maxPoints: Infinity, color: "#10B981", glowColor: "rgba(16,185,129,0.3)"   },
];

export const fanActions: FanAction[] = [
  { id: "a1",  title: "Reciclar en el estadio",       description: "Escanea el QR en los puntos de reciclaje del estadio",  points: 150, category: "fisica",   icon: "♻️", frequency: "Por partido",  completed: false },
  { id: "a2",  title: "Transporte verde",              description: "Llega al estadio en bici, transporte público o a pie",  points: 80,  category: "fisica",   icon: "🚲", frequency: "Por partido",  completed: true  },
  { id: "a3",  title: "Reto de reciclaje mensual",     description: "Sube foto de tu acción de reciclaje en casa",          points: 120, category: "fisica",   icon: "📸", frequency: "Mensual",      completed: false },
  { id: "a4",  title: "Evento sostenible del club",    description: "Asiste a un evento ESG organizado por el club",        points: 200, category: "fisica",   icon: "🌱", frequency: "Por evento",   completed: false },
  { id: "a5",  title: "Traer tus propios envases",     description: "Usa tu propia botella y envase en la cafetería",       points: 50,  category: "fisica",   icon: "🧴", frequency: "Por partido",  completed: true  },
  { id: "a6",  title: "Completar perfil ESG",          description: "Rellena todos los campos de tu perfil de fan",         points: 100, category: "digital",  icon: "👤", frequency: "Única vez",    completed: true  },
  { id: "a7",  title: "Ver reporte ESG del club",      description: "Lee el informe de sostenibilidad del club del mes",    points: 30,  category: "digital",  icon: "📊", frequency: "Mensual",      completed: false },
  { id: "a8",  title: "Quiz de sostenibilidad",        description: "Responde 5 preguntas sobre ESG y el club",            points: 60,  category: "digital",  icon: "🎯", frequency: "Mensual",      completed: true  },
  { id: "a9",  title: "Votar en proyecto ESG",         description: "Vota en las iniciativas ESG que propone el club",     points: 40,  category: "digital",  icon: "🗳️", frequency: "Por proyecto", completed: false },
  { id: "a10", title: "Referir a un fan",              description: "Invita a un amigo con tu link único",                 points: 90,  category: "digital",  icon: "🔗", frequency: "Por referido", completed: false },
  { id: "a11", title: "Compartir post ESG del club",   description: "Comparte el contenido sostenible del club en redes",  points: 50,  category: "social",   icon: "📱", frequency: "Por post",     completed: true  },
  { id: "a12", title: "Publicar con hashtag",          description: "Usa #BetterSport en tu historia de partido",         points: 70,  category: "social",   icon: "🏷️", frequency: "Por post",     completed: false },
  { id: "a13", title: "Story de partido sostenible",   description: "Sube una story mostrando tu acción verde en el partido",points: 60, category: "social",  icon: "📸", frequency: "Por partido",  completed: false },
];

export const fanRewards: FanReward[] = [
  { id: "r1", name: "20% descuento en entradas",         description: "Válido para partidos de local en la temporada",      points: 800,  type: "club",    icon: "🎫", available: true  },
  { id: "r2", name: "Camiseta edición sostenible",        description: "Camiseta exclusiva Fan ESG temporada 2025",          points: 1500, type: "club",    icon: "👕", available: false },
  { id: "r3", name: "Tour por las instalaciones",         description: "Visita guiada al estadio y centro de entrenamiento", points: 1200, type: "club",    icon: "🏟️", available: true, quota: 10 },
  { id: "r4", name: "Meet & greet con el plantel",        description: "Sesión de fotos con jugadores del primer equipo",    points: 3500, type: "club",    icon: "⭐", available: true, quota: 5  },
  { id: "r5", name: "15% en tienda online del sponsor",   description: "Descuento en tienda oficial del patrocinador",       points: 400,  type: "sponsor", icon: "🛍️", available: true  },
  { id: "r6", name: "Bebida energética gratis",           description: "Una bebida energética canjeable en el estadio",      points: 250,  type: "sponsor", icon: "🥤", available: true  },
  { id: "r7", name: "Badge · Hincha Verde 2025",          description: "Insignia digital exclusiva de la temporada",         points: 0,    type: "badge",   icon: "🏅", available: true  },
  { id: "r8", name: "Badge · Embajador Sostenible",       description: "Para fans Leyenda con 10+ acciones completadas",     points: 0,    type: "badge",   icon: "🌟", available: false },
];

export const mockFans: FanProfile[] = [
  { id: "f1",       name: "Pablo R.",     clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 4820, tier: "leyenda", actionsCompleted: 34, badgesEarned: 4, rankingPosition: 1,  joinedAt: "2025-01", completedActionIds: ["a2","a5","a6","a8","a11"], claimedRewardIds: ["r7"] },
  { id: "f2",       name: "Valentina M.", clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 4210, tier: "leyenda", actionsCompleted: 29, badgesEarned: 3, rankingPosition: 2,  joinedAt: "2025-01", completedActionIds: ["a2","a5","a6","a8"],       claimedRewardIds: ["r7"] },
  { id: "f3",       name: "Matías C.",    clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 3740, tier: "oro",     actionsCompleted: 26, badgesEarned: 2, rankingPosition: 3,  joinedAt: "2025-02", completedActionIds: ["a2","a5","a6"],           claimedRewardIds: [] },
  { id: "f4",       name: "Isadora B.",   clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 3290, tier: "oro",     actionsCompleted: 22, badgesEarned: 2, rankingPosition: 4,  joinedAt: "2025-02", completedActionIds: ["a6","a8"],               claimedRewardIds: [] },
  { id: "f5",       name: "Sebastián O.", clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 2870, tier: "oro",     actionsCompleted: 19, badgesEarned: 1, rankingPosition: 5,  joinedAt: "2025-03", completedActionIds: ["a6"],                    claimedRewardIds: [] },
  { id: "f6",       name: "Constanza V.", clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 1840, tier: "oro",     actionsCompleted: 14, badgesEarned: 1, rankingPosition: 6,  joinedAt: "2025-03", completedActionIds: ["a6","a8"],               claimedRewardIds: [] },
  { id: "f7",       name: "Diego F.",     clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 1320, tier: "plata",   actionsCompleted: 11, badgesEarned: 1, rankingPosition: 7,  joinedAt: "2025-04", completedActionIds: ["a6"],                    claimedRewardIds: [] },
  { id: "f8",       name: "Javiera A.",   clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 940,  tier: "plata",   actionsCompleted: 8,  badgesEarned: 0, rankingPosition: 8,  joinedAt: "2025-04", completedActionIds: [],                       claimedRewardIds: [] },
  { id: "f9",       name: "Nicolás E.",   clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 620,  tier: "plata",   actionsCompleted: 6,  badgesEarned: 0, rankingPosition: 9,  joinedAt: "2025-05", completedActionIds: [],                       claimedRewardIds: [] },
  { id: "f10",      name: "Andrea P.",    clubId: "c1", clubName: "Colo-Colo",   country: "Chile", flag: "🇨🇱", points: 380,  tier: "bronce",  actionsCompleted: 4,  badgesEarned: 0, rankingPosition: 10, joinedAt: "2025-05", completedActionIds: [],                       claimedRewardIds: [] },
  { id: "f-hincha", name: "Tú",           clubId: "c4", clubName: "Rugby Verde", country: "Chile", flag: "🇨🇱", points: 1240, tier: "plata",   actionsCompleted: 9,  badgesEarned: 1, rankingPosition: 47, joinedAt: "2025-03", completedActionIds: ["a2","a5","a6","a8","a11"], claimedRewardIds: ["r7"] },
];

export const fanZoneStats: FanZoneStats = {
  totalFans: 1284,
  activeFans: 490,
  participationRate: 38.2,
  totalActions: 7412,
  collectiveScore: 892000,
  rewardsRedeemed: 342,
  npsScore: 67,
  churnRate: 4.2,
  goldPlusFans: 187,
};
