import { Club, Event, ESGProject, Document, Notification, User } from "./types";

// ===== MOCK USER =====
export const mockUser: User = {
  id: "u2",
  name: "Felipe González",
  email: "felipe@clubrugby.cl",
  role: "club",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
  club: "Rugby Verde",
  country: "Chile",
  clubId: "c4",
};

// ===== MOCK USERS (one per role) =====
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Carlos Rodríguez",
    email: "carlos@bettersport.com",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    club: "BetterSport Platform",
    country: "España",
  },
  {
    id: "u2",
    name: "Felipe González",
    email: "felipe@clubrugby.cl",
    role: "club",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felipe",
    club: "Rugby Verde",
    country: "Chile",
    clubId: "c4",
  },
  {
    id: "u3",
    name: "Alejandro Reyes",
    email: "alejandro@greensportsa.com",
    role: "brand",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alejandro",
    club: "GreenSport SA",
    country: "Argentina",
  },
  {
    id: "u4",
    name: "Laura Sánchez",
    email: "laura@sportmanager.es",
    role: "manager",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Laura",
    club: "Consultora ESG Deportiva",
    country: "España",
  },
  {
    id: "u5",
    name: "Diego Fernández",
    email: "diego@auditoresg.com",
    role: "auditor",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Diego",
    club: "Auditor Certificado ESG",
    country: "México",
  },
];

// ===== MOCK CLUBS (RANKING) =====
export const mockClubs: Club[] = [
  {
    id: "c1",
    name: "Club Atlético Sostenible",
    sport: "Fútbol",
    country: "España",
    flag: "🇪🇸",
    esgScore: 94.2,
    ranking: 1,
    environmental: 96,
    social: 93,
    governance: 91,
    transparency: 98,
    members: 2400,
    founded: 1985,
    description: "Pioneros en sostenibilidad deportiva en España.",
  },
  {
    id: "c2",
    name: "Green Sports FC",
    sport: "Fútbol",
    country: "Argentina",
    flag: "🇦🇷",
    esgScore: 91.8,
    ranking: 2,
    environmental: 94,
    social: 90,
    governance: 89,
    transparency: 94,
    members: 1800,
    founded: 1992,
    description: "Referente en gestión ambiental del Cono Sur.",
  },
  {
    id: "c3",
    name: "Padel Eco Club",
    sport: "Pádel",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 88.5,
    ranking: 3,
    environmental: 90,
    social: 88,
    governance: 85,
    transparency: 91,
    members: 650,
    founded: 2005,
    description: "Inclusión y medio ambiente, nuestra razón de ser.",
  },
  {
    id: "c4",
    name: "Rugby Verde",
    sport: "Rugby",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 85.3,
    ranking: 4,
    environmental: 87,
    social: 84,
    governance: 83,
    transparency: 87,
    members: 420,
    founded: 1998,
    description: "Rugby con conciencia ambiental y social.",
  },
  {
    id: "c5",
    name: "Natación Inclusiva",
    sport: "Natación",
    country: "Colombia",
    flag: "🇨🇴",
    esgScore: 82.1,
    ranking: 5,
    environmental: 80,
    social: 90,
    governance: 79,
    transparency: 82,
    members: 310,
    founded: 2010,
    description: "Deporte adaptado e inclusión social.",
  },
  {
    id: "c6",
    name: "Tenis Sustentable",
    sport: "Tenis",
    country: "México",
    flag: "🇲🇽",
    esgScore: 79.6,
    ranking: 6,
    environmental: 82,
    social: 78,
    governance: 76,
    transparency: 83,
    members: 890,
    founded: 2001,
    description: "Promoviendo el tenis verde.",
  },
  {
    id: "c7",
    name: "Atletismo Comunitario",
    sport: "Atletismo",
    country: "Perú",
    flag: "🇵🇪",
    esgScore: 76.4,
    ranking: 7,
    environmental: 74,
    social: 82,
    governance: 74,
    transparency: 80,
    members: 520,
    founded: 2008,
    description: "Atletismo para todos.",
  },
  {
    id: "c8",
    name: "Fútbol Barrial",
    sport: "Fútbol",
    country: "Uruguay",
    flag: "🇺🇾",
    esgScore: 73.2,
    ranking: 8,
    environmental: 71,
    social: 79,
    governance: 70,
    transparency: 74,
    members: 1100,
    founded: 1975,
    description: "El fútbol como herramienta social.",
  },
  {
    id: "c9",
    name: "CrossFit Sostenible Madrid",
    sport: "CrossFit",
    country: "España",
    flag: "🇪🇸",
    esgScore: 71.4,
    ranking: 9,
    environmental: 69,
    social: 75,
    governance: 69,
    transparency: 73,
    members: 420,
    founded: 2015,
    description: "CrossFit con enfoque comunitario y sostenible en Madrid.",
  },
  {
    id: "c10",
    name: "Voleibol Ecológico Bogotá",
    sport: "Voleibol",
    country: "Colombia",
    flag: "🇨🇴",
    esgScore: 68.9,
    ranking: 10,
    environmental: 70,
    social: 72,
    governance: 64,
    transparency: 70,
    members: 280,
    founded: 2012,
    description: "Deporte y naturaleza en perfecta armonía en Bogotá.",
  },
  {
    id: "c11",
    name: "Básquetbol Social Buenos Aires",
    sport: "Básquetbol",
    country: "Argentina",
    flag: "🇦🇷",
    esgScore: 66.2,
    ranking: 11,
    environmental: 64,
    social: 70,
    governance: 65,
    transparency: 66,
    members: 650,
    founded: 2009,
    description: "Básquetbol comprometido con el desarrollo social y comunitario.",
  },
  {
    id: "c12",
    name: "Trail Running Patagonia",
    sport: "Trail Running",
    country: "Chile",
    flag: "🇨🇱",
    esgScore: 63.7,
    ranking: 12,
    environmental: 68,
    social: 62,
    governance: 59,
    transparency: 66,
    members: 190,
    founded: 2018,
    description: "Corredores de montaña con profunda conciencia ambiental.",
  },
  {
    id: "c13",
    name: "Handball Inclusivo CDMX",
    sport: "Handball",
    country: "México",
    flag: "🇲🇽",
    esgScore: 60.5,
    ranking: 13,
    environmental: 58,
    social: 67,
    governance: 57,
    transparency: 60,
    members: 340,
    founded: 2014,
    description: "Handball para todas las edades y capacidades en Ciudad de México.",
  },
  {
    id: "c14",
    name: "Ciclismo Urbano BCN",
    sport: "Ciclismo",
    country: "España",
    flag: "🇪🇸",
    esgScore: 57.8,
    ranking: 14,
    environmental: 62,
    social: 56,
    governance: 53,
    transparency: 60,
    members: 780,
    founded: 2016,
    description: "Movilidad sostenible y deporte urbano en Barcelona.",
  },
  {
    id: "c15",
    name: "Boxeo Social Lima",
    sport: "Boxeo",
    country: "Perú",
    flag: "🇵🇪",
    esgScore: 54.1,
    ranking: 15,
    environmental: 50,
    social: 62,
    governance: 51,
    transparency: 54,
    members: 210,
    founded: 2020,
    description: "Boxeo como herramienta de inclusión social en Lima.",
  },
];

// ===== MOCK EVENTS =====
export const mockEvents: Event[] = [
  {
    id: "e1",
    title: "Descarbonizando el rugby",
    clubId: "c4",
    clubName: "Rugby Verde",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Rugby",
    category: "huella_carbono",
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos y reducción de huella de carbono.",
    sustainableImpact: "Reducción del 40% de emisiones CO2 en 3 temporadas",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["Federación Rugby Chile"],
    mediaPartner: "CNN",
    sealEsg: true,
    audience: 15000,
    status: "negotiating",
  },
  {
    id: "e2",
    title: "Agua para el fútbol",
    clubId: "c2",
    clubName: "Green Sports FC",
    country: "Argentina",
    flag: "🇦🇷",
    sport: "Fútbol",
    category: "huella_hidrica",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos y eficiencia hídrica.",
    sustainableImpact: "Ahorro de 500.000 litros de agua por temporada",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["AquaEco"],
    mediaPartner: "CNN",
    sealEsg: true,
    audience: 45000,
    status: "negotiating",
  },
  {
    id: "e3",
    title: "Inclusión en Padel",
    clubId: "c3",
    clubName: "Padel Eco Club",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Pádel",
    category: "inclusion",
    image: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&q=80",
    description: "Proyecto que busca mejorar la sostenibilidad de los entornos naturales con la gestión de residuos e inclusión deportiva.",
    sustainableImpact: "200 personas con discapacidad integradas al deporte",
    budget: 120000,
    funded: 90000,
    remaining: 30000,
    daysLeft: 3,
    sponsoredBy: ["World Padel Tour"],
    mediaPartner: "ESPN",
    sealEsg: true,
    audience: 8000,
    status: "negotiating",
  },
  {
    id: "e4",
    title: "Gestión residuos en estadios",
    clubId: "c1",
    clubName: "Club Atlético Sostenible",
    country: "España",
    flag: "🇪🇸",
    sport: "Fútbol",
    category: "gestion_residuos",
    image: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=600&q=80",
    description: "Implementación de sistema de reciclaje y compostaje en estadios deportivos.",
    sustainableImpact: "Reciclaje del 80% de residuos generados en eventos",
    budget: 85000,
    funded: 60000,
    remaining: 25000,
    daysLeft: 12,
    sealEsg: false,
    audience: 60000,
    status: "open",
  },
  {
    id: "e5",
    title: "Educación ambiental juvenil",
    clubId: "c5",
    clubName: "Natación Inclusiva",
    country: "Colombia",
    flag: "🇨🇴",
    sport: "Natación",
    category: "educacion",
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?w=600&q=80",
    description: "Programa educativo para jóvenes deportistas sobre sostenibilidad y cuidado del medioambiente.",
    sustainableImpact: "1.000 jóvenes capacitados en conciencia ambiental",
    budget: 45000,
    funded: 35000,
    remaining: 10000,
    daysLeft: 21,
    sealEsg: true,
    audience: 5000,
    status: "negotiating",
  },
  {
    id: "e6",
    title: "Equidad de género en el deporte",
    clubId: "c6",
    clubName: "Tenis Sustentable",
    country: "México",
    flag: "🇲🇽",
    sport: "Tenis",
    category: "equidad_genero",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=600&q=80",
    description: "Programa de becas y formación para atletas femeninas de bajos recursos.",
    sustainableImpact: "150 mujeres acceden a formación deportiva de élite",
    budget: 65000,
    funded: 40000,
    remaining: 25000,
    daysLeft: 30,
    sealEsg: true,
    audience: 12000,
    status: "open",
  },
  {
    id: "e7",
    title: "Maratón Verde — Cero Emisiones",
    clubId: "c7",
    clubName: "Atletismo Comunitario",
    country: "Perú",
    flag: "🇵🇪",
    sport: "Atletismo",
    category: "huella_carbono",
    image: "https://images.unsplash.com/photo-1530143311094-34d807799e8f?w=600&q=80",
    description: "Maratón urbana con cero emisiones netas. Cada corredor planta un árbol al cruzar la meta.",
    sustainableImpact: "500 árboles plantados, certificación carbono neutro",
    budget: 55000,
    funded: 30000,
    remaining: 25000,
    daysLeft: 45,
    sealEsg: true,
    audience: 8000,
    status: "open",
    featured: true,
  },
  {
    id: "e8",
    title: "Rugby Femenino Sin Fronteras",
    clubId: "c4",
    clubName: "Rugby Verde",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Rugby",
    category: "equidad_genero",
    image: "https://images.unsplash.com/photo-1546519638405-a9f9a7c5d0b5?w=600&q=80",
    description: "Torneo internacional femenino de rugby con enfoque en equidad de género e inclusión.",
    sustainableImpact: "80 jugadoras de 10 países, programa de becas activo",
    budget: 78000,
    funded: 50000,
    remaining: 28000,
    daysLeft: 60,
    sponsoredBy: ["ONU Mujeres", "Nike"],
    sealEsg: true,
    audience: 22000,
    status: "open",
  },
  {
    id: "e9",
    title: "Torneo Pádel Cero Residuos",
    clubId: "c3",
    clubName: "Padel Eco Club",
    country: "Chile",
    flag: "🇨🇱",
    sport: "Pádel",
    category: "gestion_residuos",
    image: "https://images.unsplash.com/photo-1551958219-acbc595d66cf?w=600&q=80",
    description: "Torneo regional de pádel con sistema de cero residuos: sin plásticos de un solo uso y compostaje en cancha.",
    sustainableImpact: "100% residuos reciclados, 0 plásticos de un solo uso",
    budget: 35000,
    funded: 20000,
    remaining: 15000,
    daysLeft: 18,
    sealEsg: false,
    audience: 3500,
    status: "negotiating",
  },
  {
    id: "e10",
    title: "Escuela de Natación Comunitaria",
    clubId: "c5",
    clubName: "Natación Inclusiva",
    country: "Colombia",
    flag: "🇨🇴",
    sport: "Natación",
    category: "inclusion",
    image: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=600&q=80",
    description: "Escuela de natación gratuita para niños de zonas vulnerables, con énfasis en seguridad acuática y deporte inclusivo.",
    sustainableImpact: "300 niños aprenden a nadar, reducción de accidentes acuáticos",
    budget: 28000,
    funded: 28000,
    remaining: 0,
    daysLeft: 0,
    sponsoredBy: ["Fondo Nacional Deportivo", "Coldeportes"],
    sealEsg: true,
    audience: 4500,
    status: "funded",
  },
];

// ===== MOCK ESG PROJECTS =====
export const mockESGProjects: ESGProject[] = [
  {
    id: "p1",
    title: "Reducción huella de carbono 2025",
    category: "huella_carbono",
    status: "in_progress",
    progress: 65,
    budget: 45000,
    spent: 29250,
    startDate: "2025-01-15",
    endDate: "2025-12-31",
    responsible: "Carlos Mendoza",
    description: "Reducir las emisiones de CO2 del club en un 40% mediante energías renovables y movilidad sostenible.",
    milestones: [
      { id: "m1", title: "Auditoría inicial de emisiones", date: "2025-02-01", completed: true },
      { id: "m2", title: "Instalación paneles solares", date: "2025-05-01", completed: true },
      { id: "m3", title: "Flota vehículos eléctricos", date: "2025-08-01", completed: false },
      { id: "m4", title: "Certificación ISO 14001", date: "2025-12-01", completed: false },
    ],
    kpis: [
      { id: "k1", name: "Emisiones CO2 (ton)", current: 24, target: 18, unit: "ton", trend: "down" },
      { id: "k2", name: "Energía renovable (%)", current: 65, target: 100, unit: "%", trend: "up" },
    ],
  },
  {
    id: "p2",
    title: "Programa inclusión social 2025",
    category: "inclusion",
    status: "in_progress",
    progress: 80,
    budget: 28000,
    spent: 22400,
    startDate: "2025-03-01",
    endDate: "2025-11-30",
    responsible: "Ana Ruiz",
    description: "Incorporar 200 personas en situación de vulnerabilidad al deporte.",
    milestones: [
      { id: "m5", title: "Convenio municipalidad", date: "2025-03-15", completed: true },
      { id: "m6", title: "Primera cohorte inscrita", date: "2025-04-15", completed: true },
      { id: "m7", title: "Evaluación semestral", date: "2025-08-30", completed: true },
      { id: "m8", title: "Informe final y certificación", date: "2025-11-30", completed: false },
    ],
    kpis: [
      { id: "k3", name: "Personas incluidas", current: 160, target: 200, unit: "personas", trend: "up" },
      { id: "k4", name: "Tasa retención (%)", current: 82, target: 80, unit: "%", trend: "up" },
    ],
  },
  {
    id: "p3",
    title: "Gestión hídrica instalaciones",
    category: "huella_hidrica",
    status: "planning",
    progress: 20,
    budget: 18000,
    spent: 3600,
    startDate: "2025-09-01",
    endDate: "2026-03-31",
    responsible: "Pedro Soto",
    description: "Optimizar el uso del agua en canchas e instalaciones deportivas.",
    milestones: [
      { id: "m9", title: "Auditoría hídrica", date: "2025-09-30", completed: true },
      { id: "m10", title: "Sistema captación agua lluvia", date: "2025-12-01", completed: false },
      { id: "m11", title: "Riego inteligente", date: "2026-02-01", completed: false },
    ],
    kpis: [
      { id: "k5", name: "Consumo agua (m³/mes)", current: 1200, target: 800, unit: "m³", trend: "down" },
    ],
  },
  {
    id: "p4",
    title: "Equidad de género en directiva 2025",
    category: "equidad_genero",
    status: "in_progress",
    progress: 50,
    budget: 12000,
    spent: 6000,
    startDate: "2025-04-01",
    endDate: "2025-12-31",
    responsible: "María Torres",
    description: "Implementar política de género para alcanzar 40% de participación femenina en órganos directivos.",
    milestones: [
      { id: "m12", title: "Diagnóstico de brechas de género", date: "2025-04-30", completed: true },
      { id: "m13", title: "Política de género aprobada en asamblea", date: "2025-06-30", completed: true },
      { id: "m14", title: "Elecciones con cupo femenino", date: "2025-09-30", completed: false },
      { id: "m15", title: "Informe de cumplimiento anual", date: "2025-12-15", completed: false },
    ],
    kpis: [
      { id: "k6", name: "Mujeres en directiva (%)", current: 25, target: 40, unit: "%", trend: "up" },
      { id: "k7", name: "Deportistas femeninas activas", current: 85, target: 120, unit: "personas", trend: "up" },
    ],
  },
  {
    id: "p5",
    title: "Educación ambiental categorías menores",
    category: "educacion",
    status: "completed",
    progress: 100,
    budget: 8500,
    spent: 8200,
    startDate: "2025-02-01",
    endDate: "2025-07-31",
    responsible: "Sofía Morales",
    description: "Programa de 6 meses de educación ambiental para atletas menores de 18 años.",
    milestones: [
      { id: "m16", title: "Diseño curricular del programa", date: "2025-02-28", completed: true },
      { id: "m17", title: "Capacitación de monitores", date: "2025-03-31", completed: true },
      { id: "m18", title: "Implementación del programa", date: "2025-06-30", completed: true },
      { id: "m19", title: "Evaluación final y certificación", date: "2025-07-31", completed: true },
    ],
    kpis: [
      { id: "k8", name: "Jóvenes capacitados", current: 124, target: 100, unit: "personas", trend: "up" },
      { id: "k9", name: "Talleres realizados", current: 18, target: 18, unit: "talleres", trend: "stable" },
    ],
  },
];

// ===== MOCK DOCUMENTS =====
export const mockDocuments: Document[] = [
  {
    id: "d1",
    name: "Política ESG Club Rugby Chile 2025.pdf",
    type: "pdf",
    category: "Política ESG",
    size: "2.4 MB",
    uploadedAt: "2025-01-10",
    uploadedBy: "Felipe González",
    version: "v2.0",
  },
  {
    id: "d2",
    name: "Reporte Carbono Q1 2025.xlsx",
    type: "xls",
    category: "Ambiental",
    size: "845 KB",
    uploadedAt: "2025-04-05",
    uploadedBy: "Carlos Mendoza",
    version: "v1.0",
  },
  {
    id: "d3",
    name: "Certificado ISO 14001 Borrador.pdf",
    type: "pdf",
    category: "Certificaciones",
    size: "1.2 MB",
    uploadedAt: "2025-05-20",
    uploadedBy: "Felipe González",
    version: "v1.0",
  },
  {
    id: "d4",
    name: "Evidencias inclusión social - fotos.zip",
    type: "img",
    category: "Social",
    size: "18.5 MB",
    uploadedAt: "2025-06-01",
    uploadedBy: "Ana Ruiz",
    version: "v1.0",
  },
  {
    id: "d5",
    name: "Presupuesto proyectos ESG 2025.xlsx",
    type: "xls",
    category: "Financiero",
    size: "320 KB",
    uploadedAt: "2025-01-05",
    uploadedBy: "Pedro Soto",
    version: "v3.1",
  },
];

// ===== MOCK NOTIFICATIONS =====
export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "success",
    title: "Propuesta aceptada",
    message: "Claro aceptó tu propuesta de patrocinio para 'Descarbonizando el rugby'",
    time: "Hace 2 horas",
    read: false,
  },
  {
    id: "n2",
    type: "warning",
    title: "KPI fuera de meta",
    message: "El indicador de consumo hídrico supera el límite mensual",
    time: "Hace 5 horas",
    read: false,
  },
  {
    id: "n3",
    type: "info",
    title: "Nueva propuesta recibida",
    message: "ESPN envió una propuesta de media partner para 'Agua para el fútbol'",
    time: "Hace 1 día",
    read: true,
  },
  {
    id: "n4",
    type: "info",
    title: "Ranking actualizado",
    message: "Tu club subió al puesto #4 en el ranking de sostenibilidad",
    time: "Hace 2 días",
    read: true,
  },
];

// ===== ESG CATEGORY LABELS =====
export const categoryLabels: Record<string, string> = {
  huella_hidrica: "Huella hídrica",
  huella_carbono: "Huella de carbono",
  gestion_residuos: "Gestión de residuos",
  educacion: "Educación",
  inclusion: "Inclusión",
  equidad_genero: "Equidad de género",
};

export const categoryColors: Record<string, string> = {
  huella_hidrica: "badge-cyan",
  huella_carbono: "badge-green",
  gestion_residuos: "badge-orange",
  educacion: "badge-blue",
  inclusion: "badge-purple",
  equidad_genero: "badge-red",
};

export const categoryIcons: Record<string, string> = {
  huella_hidrica: "💧",
  huella_carbono: "🌱",
  gestion_residuos: "♻️",
  educacion: "📚",
  inclusion: "🤝",
  equidad_genero: "⚖️",
};
